### ISSUE TITLE
Cannot assign Opis\\Closure\\SerializableClosure to property Lcobucci\\JWT\\Configuration::$builderFactory of type Closure

### ISSUE THREAD

**Issue by lvandyk** [kmuenkel/parallel-collection#1]
Hi!

I'm trying to run a for-loop in Laravel in parallel. Each loop uses the full framework, from Eloquent, to cache etc. I get the following error when trying to run the loop:

```
Cannot assign Opis\\Closure\\SerializableClosure to property Lcobucci\\JWT\\Configuration::$builderFactory of type Closure
```

Here is the code:

```
  $handler = function($personId) {
              return 1;
  };

$before = now();
$results = collect($allPersonIds)->mapToParallel($handler)->toArray();
$after = now();

$elapsedTime = $after->diffInSeconds($before);
print_r(compact('results', 'elapsedTime'));
```

As you can see, my handler is doing very little but I still get the error The Lcobucci\JWT gets used in a middleware for my request. This code is deeper inside after the controller. 

Maybe you can point me in the correct direction?

Thank you

**Comment by kmuenkel** [comment]
Hi @lvandyk, thanks so much for your interest and for bringing this to my attention. I'm sorry it's taken a little while for me to have eyes on this project again, but I'll see what I can do about that shortly.

**Comment by kmuenkel** [comment]
What's going on is, Opis\Closure attempts to allow Php to serialize Closures by using some Reflection magic to break down its components into strings, and reconstructed it with a custom unserialize function. The way it allows for Closures to exist as object properties is by using Reflection again, and recursively following each property, replacing each Closure with an instance of SerializableClosure to allow for that breakdown to occur.

The problem comes when you have type-hinted properties. Php7.4 kind of threw Opis for a loop on that point, because suddenly the properties might be restricted and the serializable wrapper for a given closure can't be injected. Sadly the only way around that is an upcoming version 4 of that package that leverages a Php extension that essentially allows it to monkey-patch the internal 'parent class' of a Closure, and redefine it with this custom serializable logic. In the meantime, we basically just have to skip those instances and cross our fingers.

This package here makes the closures allow the use of Laravel abstractions therein by spinning up a brand new instance of the app when the closure is deserialized by AmPhp at the time it's supposed to be executed in parallel. Meaning anything that didn't actually make the leap from the main thread to the child gets replaced with a freshly-booted default. In most instances this works out just fine. For those that don't, there's not a whole lot that can be done about it.

I do have some custom logic that does attempt to retain any custom bindings that may occur in the service providers and reestablish them. They basically just try/catch their way out of any occurrences that can't be serialized. In addition, it does something similar to any request data.

So the fix I've put in place is to apply the same potential for a more silent failure if there's anything in the Request that can't be serialized too. This is a guess as to the solution though. Without more context, I'm not actually able to replicate your issue.

Can you tell me where your collection is being used, where the JWT package is being implemented, and the full stack-trace when the problem occurs?

And thank you.

**Comment by lvandyk** [comment]
Hi @kmuenkel, thank you for the detailed explanation! 

The JWT package is being used as a middleware to authenticate and bind the current user to the request.

I'll try it again with the fix that you put in place and get back to you. I'll reopen the issue if needed.
